### ISSUE TITLE
Question about Compose Video Player...

### ISSUE THREAD

**Issue by LilMoke** [Skyyo/compose-video-playback#1]
I am trying to implement the method you describe in your article and in this repository but have a question.  Why does the video take a second to play?  Even in your project when you scroll to the nest video it takes a second to play even if the sources is a has file.

Can you explain why the delay?

**Comment by Skyyo** [comment]
nor sure, if you have local file it should be kind of instant. If it's from the internet - it's natural. Also please always test final results in release mode, not debug. That makes a difference as well
